/** Stable, runtime-independent command vocabulary. Values in `args` on bindings
 * preserve legacy branch choices without asking a runtime adapter to infer them. */
export type EditorMode = "normal" | "visual" | "insert";
export type KeymapContext = "editor" | "goto" | "match" | "bracket-prev" | "bracket-next" | "view" | "sticky-view-prefix" | "sticky-view-overlay" | "sticky-view" | "ctrl-w" | "question" | "picker" | "completion" | "hover";
export type CommandOperand = "character" | "register" | "textobject" | "surround";
export interface CommandAvailability { readonly context: KeymapContext; readonly mode: EditorMode; }
export type CommandArgRule =
  | { readonly type: "boolean" }
  | { readonly type: "number" }
  | { readonly type: "string"; readonly values?: readonly string[] };
export interface CommandArgContract { readonly required?: readonly string[]; readonly defaults?: Readonly<Record<string, string | boolean | number>>; readonly properties: Readonly<Record<string, CommandArgRule>>; }
export interface CommandMetadata { id: string; description: string; modes: readonly EditorMode[]; /** Legacy extension compatibility; built-ins use availability pairs. */ contexts?: readonly KeymapContext[]; availability?: readonly CommandAvailability[]; args?: CommandArgContract; count?: boolean; async?: boolean; repeat?: boolean; history?: boolean; palette?: boolean; aliases?: readonly string[]; operand?: { readonly kind: CommandOperand; readonly arity: 1 | 2 }; }
const N = ["normal"] as const, NV = ["normal", "visual"] as const, NVI = ["normal", "visual", "insert"] as const;
const command = (id: string, description: string, modes: readonly EditorMode[] = NV, contexts: readonly KeymapContext[] = ["editor"], extra: Omit<CommandMetadata, "id" | "description" | "modes" | "contexts" | "availability"> = {}): CommandMetadata => ({ id, description, modes, contexts, availability: contexts.flatMap((context) => modes.map((mode) => ({ context, mode }))), ...extra });
const editor = (id: string, description = id, modes: readonly EditorMode[] = NV, extra: Omit<CommandMetadata, "id" | "description" | "modes" | "contexts" | "availability"> = {}) => command(id, description, modes, ["editor"], extra);
const commandCatalogSource: readonly CommandMetadata[] = [
  editor("jump.flash", "Jump to a visible target"), editor("mode.insert", "Enter insert mode", N, { count: true }), editor("mode.append", "Append in insert mode", N, { count: true }), editor("mode.insert-line-start", "Insert at first non-whitespace", N, { count: true }), editor("mode.append-line-end", "Append at line end", N, { count: true }), editor("mode.normal", "Return to normal mode", ["visual", "insert"], { count: true }), editor("mode.visual", "Toggle visual mode", NV, { count: true }),
  ...["left", "right", "up", "down"].map((x) => {
    const entry = command(`motion.${x}`, `Move ${x}`, NVI, x === "up" || x === "down" ? ["editor", "goto"] : ["editor"], { count: true });
    return x === "up" || x === "down" ? { ...entry, availability: [...NVI.map((mode) => ({ context: "editor" as const, mode })), ...NV.map((mode) => ({ context: "goto" as const, mode }))] } : entry;
  }),
  ...[["word-forward", "Move forward a word"], ["word-backward", "Move backward a word"], ["word-start", "Move to next word start"], ["W-start", "Move to next long word start"], ["B-start", "Move to previous long word"], ["E-end", "Move to long word end"]].map(([id, text]) => editor(`motion.${id}`, text, NV, { count: true })),
  command("motion.page-up", "Page up", NV, ["editor"], { count: true }), command("motion.page-down", "Page down", NV, ["editor"], { count: true }), command("motion.half-page-up", "Half page up", NV, ["editor"], { count: true }), command("motion.half-page-down", "Half page down", NV, ["editor"], { count: true }),
  ...[["file-start", "Go to file start"], ["line-start", "Go to line start"], ["line-end", "Go to line end"], ["first-non-whitespace", "Go to first non-whitespace"], ["last-line", "Go to last line"], ["window-top", "Go to window top"], ["window-center", "Go to window center"], ["window-bottom", "Go to window bottom"], ["previous-paragraph", "Previous paragraph"], ["next-paragraph", "Next paragraph"], ["matching-bracket", "Matching bracket"]].map(([id, text]) => command(`goto.${id}`, text, NV, id.includes("paragraph") ? [id.startsWith("previous") ? "bracket-prev" : "bracket-next"] : id === "matching-bracket" ? ["match"] : id === "line-start" || id === "line-end" ? ["editor", "goto"] : ["goto"], id.includes("paragraph") ? { count: true, repeat: true, args: { required: ["direction"], properties: { direction: { type: "string", values: [id.startsWith("previous") ? "previous" : "next"] } } } } : id === "matching-bracket" ? { repeat: true } : id === "window-center" ? {} : { count: true })),
  command("goto.definition", "Go to definition", NV, ["editor", "goto"], { async: true }), command("goto.references", "Go to references", NV, ["editor", "goto", "question"], { async: true }),
  command("goto.counted-line", "Go to one-based counted line", NV, ["editor", "goto"], { count: true, args: { properties: { fallback: { type: "string", values: ["first", "last"] } } } }),
  ...[["declaration", "Go to declaration"], ["type-definition", "Go to type definition"], ["implementation", "Go to implementation"]].map(([id, description]) => command(`goto.${id}`, description, NV, ["goto"], { async: true })),
  ...[["select-all", "Select all"], ["change", "Change selection"], ["delete", "Delete selection"], ["paste-after", "Paste after"], ["paste-before", "Paste before"], ["yank", "Yank selection"], ["undo", "Undo"], ["redo", "Redo"], ["open-below", "Open line below"], ["open-above", "Open line above"], ["select-line-below", "Select line below"]].map(([id, text]) => editor(`edit.${id}`, text, NV, { count: true, ...(["paste-after", "paste-before"].includes(id) ? { async: true } : {}), ...(["change", "delete", "open-below", "open-above"].includes(id) ? { history: true } : {}) })),
  editor("edit.delete-backward", "Delete backward", ["insert"], { history: true, count: true }), editor("edit.delete-forward", "Delete forward", ["insert"], { history: true, count: true }), editor("edit.newline", "Insert newline", ["insert"], { history: true, count: true }), editor("edit.indent", "Insert indentation", ["insert"], { history: true, count: true }),
  ...[
    ["collapse", "Collapse selections"], ["keep-primary", "Keep primary selection"], ["remove-primary", "Remove primary selection"], ["flip", "Flip selection direction"], ["ensure-forward", "Ensure selections face forward"],
    ["rotate-primary-forward", "Rotate primary selection forward"], ["rotate-primary-backward", "Rotate primary selection backward"], ["merge-overlapping", "Merge overlapping selections"], ["merge-consecutive", "Merge consecutive selections"], ["split-newline", "Split selections on newlines"],
    ["trim", "Trim selections"], ["join-lines", "Join selected lines"], ["join-lines-space", "Join selected lines with spaces"], ["align", "Align selection columns"], ["toggle-case", "Toggle selection case"], ["lower-case", "Lowercase selections"], ["upper-case", "Uppercase selections"],
    ["indent", "Indent selections"], ["outdent", "Outdent selections"], ["increment", "Increment selected numbers"], ["decrement", "Decrement selected numbers"]
  ].map(([id, description]) => editor(`selection.${id}`, description, NV, { palette: true, ...(["trim", "join-lines", "join-lines-space", "align", "toggle-case", "lower-case", "upper-case", "indent", "outdent", "increment", "decrement"].includes(id) ? { history: true } : {}) })),
  editor("selection.replace-character", "Replace selection characters", NV, { history: true, operand: { kind: "character", arity: 1 }, palette: true }),
  editor("selection.split-regex", "Split selections by regular expression", NV, { async: true, palette: true }),
  editor("selection.format", "Format selections", NV, { async: true, history: true, palette: true }),
  ...[["next-char", "Find next character"], ["previous-char", "Find previous character"], ["till-next-char", "Find until next character"], ["till-previous-char", "Find until previous character"]].map(([id, text]) => editor(`find.${id}`, text, NV, { operand: { kind: "character", arity: 1 }, repeat: true })),
  editor("search.forward", "Search forward", NV, { aliases: ["search", "/"], palette: true }), editor("search.backward", "Search backward", NV, { aliases: ["search-backward"], palette: true }), editor("search.selection", "Search selected text"), editor("search.repeat-next", "Repeat next search"), editor("search.repeat-previous", "Repeat previous search"),
  editor("ui.command-line", "Open command line", NV, { aliases: ["command", ":"], palette: true }), editor("ui.completion", "Request completion", NVI, { async: true }), editor("ui.signature-help", "Request signature help", NVI, { async: true, palette: true }), editor("signature.previous", "Previous signature", NVI), editor("signature.next", "Next signature", NVI), editor("signature.dismiss", "Dismiss signature help", NVI), editor("ui.file-picker", "Open file picker", NVI, { async: true, aliases: ["files"] }), editor("ui.workspace-search", "Search workspace contents", NVI, { async: true, aliases: ["global-search"], palette: true }), editor("ui.hover", "Show hover", NV, { async: true }), editor("ui.rename", "Rename symbol", NVI, { async: true, aliases: ["rename"] }), editor("ui.code-actions", "Code actions", NV, { async: true }),
  ...[["next-buffer", "Next buffer"], ["previous-buffer", "Previous buffer"], ["save-jump", "Save jump"], ["jump-back", "Jump back"], ["jump-forward", "Jump forward"]].map(([id, text]) => command(`workspace.${id}`, text, NV, id.endsWith("buffer") ? ["goto"] : ["editor"], id.startsWith("jump-") ? { async: true } : {})),
  editor("history.checkpoint", "Checkpoint history", ["insert"]), editor("register.select", "Select register", NV, { operand: { kind: "register", arity: 1 } }), editor("register.insert", "Insert selected register", ["insert"], { async: true, operand: { kind: "register", arity: 1 } }),
  editor("prefix.goto", "Go-to prefix"), editor("prefix.match", "Match prefix"), editor("prefix.bracket-prev", "Previous bracket prefix"), editor("prefix.bracket-next", "Next bracket prefix"), editor("prefix.view", "View prefix"), editor("prefix.sticky-view", "Sticky view prefix"), editor("prefix.question", "Help prefix"), editor("prefix.ctrl-w", "Window prefix"),
  command("comment.toggle", "Toggle line comment", NV, ["goto"], { async: true }), editor("comment.smart", "Toggle smart comment", NV, { async: true }),
  ...[["next", "Next syntax target"], ["previous", "Previous syntax target"]].map(([id, text]) => command(`syntax.${id}`, text, NV, [id === "next" ? "bracket-next" : "bracket-prev"], { async: true, args: { required: ["target"], properties: { target: { type: "string", values: ["f", "t", "a", "c", "T", "g", "x"] } } } })), editor("syntax.select-up", "Expand syntax selection", NV, { async: true }), editor("syntax.select-down", "Shrink syntax selection", NV, { async: true }), editor("repeat.motion", "Repeat motion", NV, { async: true }), editor("repeat.edit", "Repeat last completed edit", NV, { async: true, count: true, repeat: true, history: true }),
  command("textobject.select", "Select text object", NV, ["match"], { async: true, operand: { kind: "textobject", arity: 1 }, repeat: true, args: { required: ["scope"], properties: { scope: { type: "string", values: ["inside", "around"] } } } }), command("surround.add", "Add surround", NV, ["match"], { operand: { kind: "surround", arity: 1 } }), command("surround.delete", "Delete surround", NV, ["match"], { operand: { kind: "surround", arity: 1 } }), command("surround.replace", "Replace surround", NV, ["match"], { operand: { kind: "surround", arity: 2 } }),
  ...[["buffers", "show buffers (g n / g p cycle)"], ["diagnostics", "show diagnostics"], ["jumps", "show jumplist"], ["panes", "show panes (Ctrl-w window mode)"], ["symbols-document", "show document symbols"], ["symbols-workspace", "show workspace symbols"]].map(([id, text]) => command(`picker.${id}`, text, NV, ["question"], { async: id.startsWith("symbols") })),
  ...[["split-vertical", "Split vertically"], ["split-horizontal", "Split horizontally"], ["close-pane", "Close pane"], ["only-pane", "Only pane"], ["focus-next-pane", "Focus next pane"], ["focus-left", "Focus left"], ["focus-right", "Focus right"], ["focus-up", "Focus up"], ["focus-down", "Focus down"], ["swap-left", "Swap left"], ["swap-right", "Swap right"], ["swap-up", "Swap up"], ["swap-down", "Swap down"], ["open-selection-horizontal", "Open selection horizontally"], ["open-selection-vertical", "Open selection vertically"], ["new-scratch-horizontal", "New scratch split"]].map(([id, text]) => command(`workspace.${id}`, text, NV, ["ctrl-w"], { async: id.startsWith("open-selection") })),
  ...[["center", "Center selection"], ["top", "Align selection top"], ["bottom", "Align selection bottom"], ["scroll-up", "Scroll up"], ["scroll-down", "Scroll down"]].map(([id, text]) => command(`view.${id}`, text, NV, id === "scroll-up" || id === "scroll-down" ? ["view", "sticky-view-prefix", "sticky-view-overlay", "sticky-view"] : ["view", "sticky-view-prefix"], { args: { required: id === "center" || id === "top" || id === "bottom" ? ["alignment", "sticky"] : ["sticky"], properties: { ...(id === "center" || id === "top" || id === "bottom" ? { alignment: { type: "string" as const, values: [id] } } : {}), sticky: { type: "boolean" } } } })),
  ...[["page-up", "Page viewport up"], ["page-down", "Page viewport down"], ["half-page-up", "Half-page viewport up"], ["half-page-down", "Half-page viewport down"]].map(([id, text]) => command(`view.${id}`, text, NVI, ["sticky-view"])),
  command("view.exit-sticky", "Exit sticky view mode", NV, ["sticky-view-overlay", "sticky-view"]),
  command("completion.previous", "Previous completion", NVI, ["completion"]), command("completion.next", "Next completion", NVI, ["completion"]), command("completion.accept", "Accept completion", NVI, ["completion"], { async: true }), command("completion.dismiss", "Dismiss completion", NVI, ["completion"]),
  command("picker.previous", "Previous picker item", NVI, ["picker"], { args: { properties: { variant: { type: "string", values: ["bar"] } } } }), command("picker.next", "Next picker item", NVI, ["picker"], { args: { properties: { variant: { type: "string", values: ["bar"] } } } }), command("picker.accept", "Accept picker item", NVI, ["picker"], { async: true }), command("picker.dismiss", "Dismiss picker", NVI, ["picker"]), command("picker.delete-backward", "Delete picker query backward", NVI, ["picker"], { async: true }), command("hover.dismiss", "Dismiss hover", NVI, ["hover"]),
  ...[["horizontal", "Open picker result in horizontal split"], ["vertical", "Open picker result in vertical split"], ["background", "Open picker result in background"]].map(([id, description]) => command(`picker.accept-${id}`, description, NVI, ["picker"], { async: true })),
  command("diagnostic.next", "Next diagnostic", NV, ["bracket-next"], { args: { defaults: { extreme: false }, properties: { extreme: { type: "boolean" } } } }), command("diagnostic.previous", "Previous diagnostic", NV, ["bracket-prev"], { args: { defaults: { extreme: false }, properties: { extreme: { type: "boolean" } } } })
];
function deepFreeze<T>(value: T): T {
  if (!value || typeof value !== "object" || Object.isFrozen(value)) return value;
  for (const child of Object.values(value as Record<string, unknown>)) deepFreeze(child);
  return Object.freeze(value);
}
function readonlyMapView<K, V>(source: Map<K, V>): ReadonlyMap<K, V> {
  let view: ReadonlyMap<K, V>;
  view = Object.freeze({
    get size() { return source.size; },
    has(key: K) { return source.has(key); },
    get(key: K) { return source.get(key); },
    entries() { return source.entries(); },
    keys() { return source.keys(); },
    values() { return source.values(); },
    forEach(callback: (value: V, key: K, map: ReadonlyMap<K, V>) => void, thisArg?: unknown) {
      source.forEach((value, key) => callback.call(thisArg, value, key, view));
    },
    [Symbol.iterator]() { return source[Symbol.iterator](); }
  });
  return view;
}
export const commandCatalog: readonly CommandMetadata[] = Object.freeze(commandCatalogSource.map((entry) => deepFreeze(entry)));
export const completeCommandCatalog = commandCatalog;
export const commandCatalogById: ReadonlyMap<string, CommandMetadata> = readonlyMapView(new Map(commandCatalog.map((entry) => [entry.id, entry])));
export function resolveCommandId(id: string, catalog: ReadonlyMap<string, CommandMetadata> = commandCatalogById): string | null { if (catalog.has(id)) return id; const owners = [...catalog.values()].filter((entry) => entry.aliases?.includes(id)); return owners.length === 1 ? owners[0]!.id : null; }
