import type { EditorMode } from "./command-catalog";
import type { KeymapBinding } from "./keymap-schema";
const NV = ["normal", "visual"] as const satisfies readonly EditorMode[];
const NVI = ["normal", "visual", "insert"] as const satisfies readonly EditorMode[];
const both = (keys: string, command: string, args?: KeymapBinding["args"]): KeymapBinding => ({ keys, command, modes: NV, ...(args ? { args } : {}) });
const inContext = (context: NonNullable<KeymapBinding["context"]>, keys: string, command: string, args?: KeymapBinding["args"]): KeymapBinding => ({ context, keys, command, modes: NV, ...(args ? { args } : {}) });
const inAnyModeContext = (context: NonNullable<KeymapBinding["context"]>, keys: string, command: string, args?: KeymapBinding["args"]): KeymapBinding => ({ context, keys, command, modes: NVI, ...(args ? { args } : {}) });
const direct: [string, string][] = [
  ["%", "edit.select-all"], [".", "repeat.edit"], ["B", "motion.B-start"], ["E", "motion.E-end"], ["End", "goto.line-end"], ["Home", "goto.line-start"], ["P", "edit.paste-before"], ["PageDown", "motion.page-down"], ["PageUp", "motion.page-up"], ["W", "motion.W-start"], ["b", "motion.word-backward"], ["c", "edit.change"], ["d", "edit.delete"], ["e", "motion.word-forward"], ["o", "edit.open-below"], ["O", "edit.open-above"], ["p", "edit.paste-after"], ["u", "edit.undo"], ["U", "edit.redo"], ["w", "motion.word-start"], ["x", "edit.select-line-below"], ["y", "edit.yank"],
  ["h", "motion.left"], ["l", "motion.right"], ["k", "motion.up"], ["j", "motion.down"], ["ArrowLeft", "motion.left"], ["ArrowRight", "motion.right"], ["ArrowUp", "motion.up"], ["ArrowDown", "motion.down"],
  ["Space", "jump.flash"], ["f", "find.next-char"], ["F", "find.previous-char"], ["t", "find.till-next-char"], ["T", "find.till-previous-char"], ["*", "search.selection"], ["n", "search.repeat-next"], ["N", "search.repeat-previous"], [":", "ui.command-line"], ["/", "search.forward"], ["\"", "register.select"],
  ["r", "selection.replace-character"], ["~", "selection.toggle-case"], ["`", "selection.lower-case"], ["Alt+`", "selection.upper-case"], [">", "selection.indent"], ["<", "selection.outdent"], ["=", "selection.format"], ["Ctrl+a", "selection.increment"], ["Ctrl+x", "selection.decrement"],
  ["S", "selection.split-regex"], ["Alt+s", "selection.split-newline"], ["Alt+-", "selection.merge-overlapping"], ["Alt+_", "selection.merge-consecutive"], ["&", "selection.align"], ["_", "selection.trim"], [";", "selection.collapse"], ["Alt+;", "selection.flip"], ["Alt+:", "selection.ensure-forward"], [",", "selection.keep-primary"], ["Alt+,", "selection.remove-primary"], ["(", "selection.rotate-primary-backward"], [")", "selection.rotate-primary-forward"], ["J", "selection.join-lines"], ["Alt+J", "selection.join-lines-space"],
  ["g", "prefix.goto"], ["[", "prefix.bracket-prev"], ["]", "prefix.bracket-next"], ["m", "prefix.match"], ["z", "prefix.view"], ["Z", "prefix.sticky-view"], ["?", "prefix.question"], ["Ctrl+w", "prefix.ctrl-w"],
  ["Alt+g", "goto.definition"], ["Alt+G", "goto.references"], ["Alt+k", "ui.hover"], ["Alt+K", "ui.hover"], ["Alt+r", "ui.rename"], ["Alt+R", "ui.rename"], ["Alt+/", "comment.smart"], ["Alt+*", "search.selection"], ["Alt+.", "repeat.motion"], ["Alt+ArrowUp", "syntax.select-up"], ["Alt+ArrowDown", "syntax.select-down"], ["Ctrl+s", "workspace.save-jump"], ["Ctrl+o", "workspace.jump-back"], ["Ctrl+i", "workspace.jump-forward"], ["Ctrl+.", "ui.code-actions"], ["Ctrl+,", "ui.hover"], ["Ctrl+Space", "ui.completion"], ["Ctrl+p", "ui.file-picker"], ["F2", "ui.rename"], ["Ctrl+b", "motion.page-up"], ["Ctrl+f", "motion.page-down"], ["Ctrl+u", "motion.half-page-up"], ["Ctrl+d", "motion.half-page-down"]
  ,["Ctrl+k", "ui.signature-help"], ["Alt+PageUp", "signature.previous"], ["Alt+PageDown", "signature.next"], ["Ctrl+F", "ui.workspace-search"]
];
const goto: [string, string][] = [["g", "goto.counted-line"], ["b", "goto.window-bottom"], ["c", "comment.toggle"], ["d", "goto.definition"], ["D", "goto.declaration"], ["y", "goto.type-definition"], ["i", "goto.implementation"], ["r", "goto.references"], ["e", "goto.last-line"], ["h", "goto.line-start"], ["j", "motion.down"], ["k", "motion.up"], ["l", "goto.line-end"], ["s", "goto.first-non-whitespace"], ["t", "goto.window-top"], ["n", "workspace.next-buffer"], ["p", "workspace.previous-buffer"]];
const ctrlW: [string, string][] = [
  ...["v", "V", "Ctrl+v", "Ctrl+V"].map((keys) => [keys, "workspace.split-vertical"] as [string, string]), ...["s", "S", "Ctrl+s", "Ctrl+S"].map((keys) => [keys, "workspace.split-horizontal"] as [string, string]), ...["q", "Q", "Ctrl+q", "Ctrl+Q"].map((keys) => [keys, "workspace.close-pane"] as [string, string]), ...["o", "O", "Ctrl+o", "Ctrl+O"].map((keys) => [keys, "workspace.only-pane"] as [string, string]), ...["w", "W", "Ctrl+w", "Ctrl+W"].map((keys) => [keys, "workspace.focus-next-pane"] as [string, string]),
  ["h", "workspace.focus-left"], ["Ctrl+h", "workspace.focus-left"], ["ArrowLeft", "workspace.focus-left"], ["j", "workspace.focus-down"], ["Ctrl+j", "workspace.focus-down"], ["ArrowDown", "workspace.focus-down"], ["k", "workspace.focus-up"], ["Ctrl+k", "workspace.focus-up"], ["ArrowUp", "workspace.focus-up"], ["l", "workspace.focus-right"], ["Ctrl+l", "workspace.focus-right"], ["ArrowRight", "workspace.focus-right"], ...["H", "Ctrl+H"].map((keys) => [keys, "workspace.swap-left"] as [string, string]), ...["J", "Ctrl+J"].map((keys) => [keys, "workspace.swap-down"] as [string, string]), ...["K", "Ctrl+K"].map((keys) => [keys, "workspace.swap-up"] as [string, string]), ...["L", "Ctrl+L"].map((keys) => [keys, "workspace.swap-right"] as [string, string]), ["f", "workspace.open-selection-horizontal"], ["Ctrl+f", "workspace.open-selection-horizontal"], ["F", "workspace.open-selection-vertical"], ["Ctrl+F", "workspace.open-selection-vertical"], ...["n", "N", "Ctrl+n", "Ctrl+N"].map((keys) => [keys, "workspace.new-scratch-horizontal"] as [string, string])
];
const defaultKeymapSource: readonly KeymapBinding[] = [
  ...direct.map(([keys, command]) => both(keys, command)), both("G", "goto.counted-line", { fallback: "last" }), { keys: "i", command: "mode.insert", modes: ["normal"] }, { keys: "a", command: "mode.append", modes: ["normal"] }, { keys: "I", command: "mode.insert-line-start", modes: ["normal"] }, { keys: "A", command: "mode.append-line-end", modes: ["normal"] }, { keys: "v", command: "mode.visual", modes: ["normal", "visual"] }, { keys: "Escape", command: "signature.dismiss", modes: ["normal"] }, { keys: "Escape", command: "mode.normal", modes: ["visual", "insert"] },
  { keys: "Tab", command: "edit.indent", modes: ["insert"] }, { keys: "Enter", command: "edit.newline", modes: ["insert"] }, { keys: "Backspace", command: "edit.delete-backward", modes: ["insert"] }, { keys: "Delete", command: "edit.delete-forward", modes: ["insert"] }, ...(["ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown"] as const).map((keys) => ({ keys, command: `motion.${keys.slice(5).replace("Left", "left").replace("Right", "right").replace("Up", "up").replace("Down", "down")}`, modes: ["insert"] as const })),
  { keys: "Ctrl+Space", command: "ui.completion", modes: ["insert"] }, { keys: "Ctrl+F", command: "ui.workspace-search", modes: ["insert"] }, { keys: "Ctrl+k", command: "ui.signature-help", modes: ["insert"] }, { keys: "Alt+PageUp", command: "signature.previous", modes: ["insert"] }, { keys: "Alt+PageDown", command: "signature.next", modes: ["insert"] }, { keys: "Ctrl+p", command: "ui.file-picker", modes: ["insert"] }, { keys: "F2", command: "ui.rename", modes: ["insert"] }, { keys: "Ctrl+s", command: "history.checkpoint", modes: ["insert"] }, { keys: "Ctrl+r", command: "register.insert", modes: ["insert"] },
  ...goto.map(([keys, command]) => inContext("goto", keys, command, keys === "g" ? { fallback: "first" } : undefined)),
  ...([["p", "goto.previous-paragraph", { direction: "previous" }], ["d", "diagnostic.previous", { extreme: false }], ["D", "diagnostic.previous", { extreme: true }]] as const).map(([keys, command, args]) => inContext("bracket-prev", keys, command, args)), ...([["p", "goto.next-paragraph", { direction: "next" }], ["d", "diagnostic.next", { extreme: false }], ["D", "diagnostic.next", { extreme: true }]] as const).map(([keys, command, args]) => inContext("bracket-next", keys, command, args)),
  ...(["f", "t", "a", "c", "T", "g", "x"] as const).flatMap((keys) => [inContext("bracket-prev", keys, "syntax.previous", { target: keys }), inContext("bracket-next", keys, "syntax.next", { target: keys })]),
  inContext("match", "m", "goto.matching-bracket"), inContext("match", "a", "textobject.select", { scope: "around" }), inContext("match", "i", "textobject.select", { scope: "inside" }), inContext("match", "s", "surround.add"), inContext("match", "d", "surround.delete"), inContext("match", "r", "surround.replace"),
  ...ctrlW.map(([keys, command]) => inContext("ctrl-w", keys, command)),
  ...([["b", "picker.buffers"], ["B", "picker.buffers"], ["d", "picker.diagnostics"], ["j", "picker.jumps"], ["p", "picker.panes"], ["s", "picker.symbols-document"], ["S", "picker.symbols-workspace"], ["r", "goto.references"]] as const).map(([keys, command]) => inContext("question", keys, command)),
  ...(["view", "sticky-view-prefix"] as const).flatMap((context) => [["z", "view.center", { alignment: "center", sticky: context === "sticky-view-prefix" }], ["c", "view.center", { alignment: "center", sticky: context === "sticky-view-prefix" }], ["m", "view.center", { alignment: "center", sticky: context === "sticky-view-prefix" }], ["t", "view.top", { alignment: "top", sticky: context === "sticky-view-prefix" }], ["b", "view.bottom", { alignment: "bottom", sticky: context === "sticky-view-prefix" }], ["j", "view.scroll-down", { sticky: context === "sticky-view-prefix" }], ["k", "view.scroll-up", { sticky: context === "sticky-view-prefix" }]].map(([keys, command, args]) => inContext(context, keys as string, command as string, args as KeymapBinding["args"]))),
  ...(["j", "k", "ArrowUp", "ArrowDown"] as const).map((keys) => inContext("sticky-view-overlay", keys, keys === "j" || keys === "ArrowDown" ? "view.scroll-down" : "view.scroll-up", { sticky: true })), inContext("sticky-view-overlay", "Escape", "view.exit-sticky"),
  ...(["j", "k", "ArrowUp", "ArrowDown"] as const).map((keys) => inContext("sticky-view", keys, keys === "j" || keys === "ArrowDown" ? "view.scroll-down" : "view.scroll-up", { sticky: true })), ...(["Ctrl+b", "Ctrl+f", "Ctrl+u", "Ctrl+d"] as const).map((keys) => inAnyModeContext("sticky-view", keys, `view.${keys === "Ctrl+b" ? "page-up" : keys === "Ctrl+f" ? "page-down" : keys === "Ctrl+u" ? "half-page-up" : "half-page-down"}`)), inContext("sticky-view", "Escape", "view.exit-sticky"),
  ...([["ArrowUp", "completion.previous"], ["Shift+Tab", "completion.previous"], ["ArrowDown", "completion.next"], ["Tab", "completion.next"], ["Enter", "completion.accept"], ["Escape", "completion.dismiss"]] as const).map(([keys, command]) => inAnyModeContext("completion", keys, command)),
  ...([["H", "picker.accept-horizontal", undefined], ["V", "picker.accept-vertical", undefined], ["B", "picker.accept-background", undefined], ["ArrowUp", "picker.previous", undefined], ["ArrowLeft", "picker.previous", { variant: "bar" }], ["h", "picker.previous", { variant: "bar" }], ["ArrowDown", "picker.next", undefined], ["ArrowRight", "picker.next", { variant: "bar" }], ["l", "picker.next", { variant: "bar" }], ["Enter", "picker.accept", undefined], ["Escape", "picker.dismiss", undefined], ["Backspace", "picker.delete-backward", undefined]] as const).map(([keys, command, args]) => inAnyModeContext("picker", keys, command, args)), inAnyModeContext("hover", "Escape", "hover.dismiss")
];
export const defaultKeymap: readonly KeymapBinding[] = Object.freeze(defaultKeymapSource.map((binding) => Object.freeze({
  ...binding,
  ...(Array.isArray(binding.keys) ? { keys: Object.freeze([...binding.keys]) } : {}),
  ...(binding.modes ? { modes: Object.freeze([...binding.modes]) } : {}),
  ...(binding.args ? { args: Object.freeze({ ...binding.args }) } : {})
})));
